name: tf311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.13
  - numpy=2.0.2
  - scipy=1.16.1
  - matplotlib=3.10.0
  - scikit-learn=1.6.1
  - pillow=11.3.0
  - beautifulsoup4=4.13.4
  - pydot=3.0.4
  - graphviz       # pydot 시각화에 필요
  - ipykernel      # Jupyter/VSCode 노트북 커널 등록
  - pip
  - pip:
      - tensorflow==2.19.0
# conda env create -f environment.yml 로 환경 생성
# conda activate tf311 로 환경 활성화